#!/usr/bin/env python3

# Copyright (c) 2018 NVIDIA Corporation. All rights reserved.
# This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
# https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode

"""
This file starts a ROS node to run DOPE, 
listening to an image topic and publishing poses.
"""

from __future__ import print_function

import cv2
import math
import message_filters
import numpy as np
import resource_retriever
import rospy
import tf.transformations
from PIL import Image
from PIL import ImageDraw
from cv_bridge import CvBridge
from dope.inference.cuboid import Cuboid3d
from dope.inference.cuboid_pnp_solver import CuboidPNPSolver
from dope.inference.detector import ModelData, ObjectDetector
from geometry_msgs.msg import PoseStamped, Quaternion
from geometry_msgs.msg import Pose2D
from sensor_msgs.msg import CameraInfo, Image as ImageSensor_msg
from std_msgs.msg import String
from vision_msgs.msg import Detection3D, Detection3DArray, ObjectHypothesisWithPose
from visualization_msgs.msg import Marker, MarkerArray


class Draw(object):
    """Drawing helper class to visualize the neural network output"""

    def __init__(self, im):
        """
        :param im: The image to draw in.
        """
        self.draw = ImageDraw.Draw(im)

    def draw_line(self, point1, point2, line_color, line_width=2):
        """Draws line on image"""
        if point1 is not None and point2 is not None:
            self.draw.line([point1, point2], fill=line_color, width=line_width)

    def draw_dot(self, point, point_color, point_radius):
        """Draws dot (filled circle) on image"""
        if point is not None:
            xy = [
                point[0] - point_radius,
                point[1] - point_radius,
                point[0] + point_radius,
                point[1] + point_radius
            ]
            self.draw.ellipse(xy,
                              fill=point_color,
                              outline=point_color
                              )

    def draw_cube(self, points, color=(255, 0, 0)):
        """
        Draws cube with a thick solid line across
        the front top edge and an X on the top face.
        """

        # draw front
        self.draw_line(points[0], points[1], color)
        self.draw_line(points[1], points[2], color)
        self.draw_line(points[3], points[2], color)
        self.draw_line(points[3], points[0], color)

        # draw back
        self.draw_line(points[4], points[5], color)
        self.draw_line(points[6], points[5], color)
        self.draw_line(points[6], points[7], color)
        self.draw_line(points[4], points[7], color)

        # draw sides
        self.draw_line(points[0], points[4], color)
        self.draw_line(points[7], points[3], color)
        self.draw_line(points[5], points[1], color)
        self.draw_line(points[2], points[6], color)

        # draw dots
        self.draw_dot(points[0], point_color=color, point_radius=4)
        self.draw_dot(points[1], point_color=color, point_radius=4)

        # draw x on the top
        self.draw_line(points[0], points[5], color)
        self.draw_line(points[1], points[4], color)


class DopeNode(object):
    """ROS node that listens to image topic, runs DOPE, and publishes DOPE results"""
    def __init__(self):
        self.pubs = {}
        self.pub_comp = {}
        self.pub_2DPosition = {}
        self.models = {}
        self.pnp_solvers = {}
        self.pub_dimension = {}
        self.pub_belief = {}
        self.draw_colors = {}
        self.dimensions = {}
        self.class_ids = {}
        self.model_transforms = {}
        self.meshes = {}
        self.mesh_scales = {}
        self.cv_bridge = CvBridge()
        self.prev_num_detections = 0
        # self.waiting = False#
        # self.received = False#

        self.input_is_rectified = rospy.get_param('~input_is_rectified', True)
        self.downscale_height = rospy.get_param('~downscale_height', 500)
        self.overlay_belief_images = rospy.get_param('~overlay_belief_images', True)

        self.config_detect = lambda: None
        self.config_detect.mask_edges = 1
        self.config_detect.mask_faces = 1
        self.config_detect.vertex = 1
        self.config_detect.threshold = 0.5
        self.config_detect.softmax = 1000
        self.config_detect.thresh_angle = rospy.get_param('~thresh_angle', 0.5)
        self.config_detect.thresh_map = rospy.get_param('~thresh_map', 0.01)
        self.config_detect.sigma = rospy.get_param('~sigma', 3)
        self.config_detect.thresh_points = rospy.get_param("~thresh_points", 0.1)
        self.config_detect.dimensions = rospy.get_param("~dimensions", 0)#
        self.config_detect.weights_name = rospy.get_param("~weights", 0)#
        self.config_detect.object_name = list(self.config_detect.weights_name.keys())[0]#
        print('object name:', self.config_detect.object_name)#
        print('dimension:', self.config_detect.dimensions[self.config_detect.object_name])#
        print('dimension along z:', self.config_detect.dimensions[self.config_detect.object_name][2])#
        

        # For each object to detect, load network model, create PNP solver, and start ROS publishers
        for model, weights_url in rospy.get_param('~weights').items():
            print('model:', model)#
            self.models[model] = \
                ModelData(
                    model,
                    resource_retriever.get_filename(weights_url, use_protocol=False)
                )
            self.models[model].load_net_model()

            try:
                M = np.array(rospy.get_param('~model_transforms')[model], dtype='float64')
                self.model_transforms[model] = tf.transformations.quaternion_from_matrix(M)
            except KeyError:
                self.model_transforms[model] = np.array([0.0, 0.0, 0.0, 1.0], dtype='float64')

            try:
                self.meshes[model] = rospy.get_param('~meshes')[model]
            except KeyError:
                pass

            try:
                self.mesh_scales[model] = rospy.get_param('~mesh_scales')[model]
            except KeyError:
                self.mesh_scales[model] = 1.0
            try:
                self.draw_colors[model] = tuple(rospy.get_param("~draw_colors")[model])
            except:
                self.draw_colors[model] = (np.random.randint(0,255),np.random.randint(0,255),np.random.randint(0,255))

            self.dimensions[model] = tuple(rospy.get_param("~dimensions")[model])
            self.class_ids[model] = rospy.get_param("~class_ids")[model]

            self.pnp_solvers[model] = \
                CuboidPNPSolver(
                    model,
                    cuboid3d=Cuboid3d(rospy.get_param('~dimensions')[model])
                )
            self.pubs[model] = \
                rospy.Publisher(
                    '{}/pose_{}'.format(rospy.get_param('~topic_publishing'), model),
                    PoseStamped,
                    queue_size=10
                )
            self.pub_comp[model] = \
                rospy.Publisher(
                    '{}/pose_comp'.format(rospy.get_param('~topic_publishing')),
                    PoseStamped,
                    queue_size=10
                )
            self.pub_2DPosition[model] = \
                rospy.Publisher(
                    '{}/pose2d_{}'.format(rospy.get_param('~topic_publishing'), model),
                    Pose2D,
                    queue_size=10
                )
            self.pub_dimension[model] = \
                rospy.Publisher(
                    '{}/dimension_{}'.format(rospy.get_param('~topic_publishing'), model),
                    String,
                    queue_size=10
                )
            self.pub_belief[model] = \
                rospy.Publisher(
                    '{}/belief_{}'.format(rospy.get_param('~topic_publishing'), model),
                    ImageSensor_msg,
                    queue_size=10
                )

        # Start ROS publishers
        self.pub_rgb_dope_points = \
            rospy.Publisher(
                rospy.get_param('~topic_publishing') + "/rgb_points",
                ImageSensor_msg,
                queue_size=10
            )
        self.pub_camera_info = \
            rospy.Publisher(
                rospy.get_param('~topic_publishing') + "/camera_info",
                CameraInfo,
                queue_size=10
            )
        self.pub_detections = \
            rospy.Publisher(
                '~detected_objects',
                Detection3DArray,
                queue_size=10
            )
        self.pub_markers = \
            rospy.Publisher(
                '~markers',
                MarkerArray,
                queue_size=10
            )

        # Start ROS subscriber
        image_sub = message_filters.Subscriber(
            rospy.get_param('~topic_camera'),
            ImageSensor_msg
        )
        info_sub = message_filters.Subscriber(
            rospy.get_param('~topic_camera_info'),
            CameraInfo
        )
        depth_sub = message_filters.Subscriber(
            rospy.get_param('~topic_depth'),
            ImageSensor_msg
        )
        depth_info_sub = message_filters.Subscriber(
            rospy.get_param('~topic_depth_info'),
            CameraInfo
        )
        ts = message_filters.TimeSynchronizer([image_sub, info_sub, depth_sub], 1)
        ts.registerCallback(self.image_callback)
        # message_filters.Subscriber(rospy.get_param('~topic_depth'), Image, self._depth_img_callback, queue_size=1)

        print("Running DOPE...  (Listening to camera topic: '{}')".format(rospy.get_param('~topic_camera')))
        print("...  (Listening to depth topic: '{}')".format(rospy.get_param('~topic_depth')))        
        print("Ctrl-C to stop")


    def quaternion_to_matrix(self, Q):
        return np.array([
            [1 - 2*Q.y*Q.y - 2*Q.z*Q.z,     2*Q.x*Q.y - 2*Q.z*Q.w,     2*Q.x*Q.z + 2*Q.y*Q.w],
            [    2*Q.x*Q.y + 2*Q.z*Q.w, 1 - 2*Q.x*Q.x - 2*Q.z*Q.z,     2*Q.y*Q.z - 2*Q.x*Q.w],
            [    2*Q.x*Q.z - 2*Q.y*Q.w,     2*Q.y*Q.z + 2*Q.x*Q.w, 1 - 2*Q.x*Q.x - 2*Q.y*Q.y]])

    def matrix_to_quaternion(self, R):
        q = Quaternion()
        q.w = math.sqrt(1.0 + R[0, 0] + R[1, 1] + R[2, 2]) * 0.5
        q.x = (R[2, 1] - R[1, 2]) / (4 * q.w)
        q.y = (R[0, 2] - R[2, 0]) / (4 * q.w)
        q.z = (R[1, 0] - R[0, 1]) / (4 * q.w)
        return q

    # def _depth_img_callback(self, depth_msg):#
    #     # Doing a rospy.wait_for_message is super slow, compared to just subscribing and keeping the newest one.
    #     if not self.waiting:
    #       return
    #     self.curr_depth_img = self.cv_bridge.imgmsg_to_cv2(depth_msg)
    #     self.received = True

    def image_callback(self, image_msg, camera_info, depth_msg):
        """Image callback"""

        img = self.cv_bridge.imgmsg_to_cv2(image_msg, "rgb8")
        # cv2.imwrite('img.png', cv2.cvtColor(img, cv2.COLOR_BGR2RGB))  # for debugging

        # Update camera matrix and distortion coefficients
        if self.input_is_rectified:
            P = np.matrix(camera_info.P, dtype='float64')
            P.resize((3, 4))
            camera_matrix = P[:, :3]
            dist_coeffs = np.zeros((4, 1))
        else:
            camera_matrix = np.matrix(camera_info.K, dtype='float64')
            camera_matrix.resize((3, 3))
            dist_coeffs = np.matrix(camera_info.D, dtype='float64')
            dist_coeffs.resize((len(camera_info.D), 1))

        # Downscale image if necessary
        height, width, _ = img.shape
        scaling_factor = float(self.downscale_height) / height
        if scaling_factor < 1.0:
            camera_matrix[:2] *= scaling_factor
            img = cv2.resize(img, (int(scaling_factor * width), int(scaling_factor * height)))

        for m in self.models:
            self.pnp_solvers[m].set_camera_intrinsic_matrix(camera_matrix)
            self.pnp_solvers[m].set_dist_coeffs(dist_coeffs)

        # Copy and draw image
        img_copy = img.copy()
        im = Image.fromarray(img_copy)
        draw = Draw(im)

        detection_array = Detection3DArray()
        detection_array.header = image_msg.header

        for m in self.models:
            publish_belief_img = (self.pub_belief[m].get_num_connections() > 0)

            # Detect object
            results, im_belief = ObjectDetector.detect_object_in_image(
                self.models[m].net,
                self.pnp_solvers[m],
                img,
                self.config_detect,
                make_belief_debug_img=publish_belief_img,
                overlay_image=self.overlay_belief_images
            )

            # Publish pose and overlay cube on image
            z_min = 1.0#
            pose_comp = PoseStamped()#
            for i_r, result in enumerate(results):
                if result["location"] is None:
                    continue
                loc = result["location"]
                ori = result["quaternion"]

                # transform orientation
                transformed_ori = tf.transformations.quaternion_multiply(ori, self.model_transforms[m])

                # rotate bbox dimensions if necessary
                # (this only works properly if model_transform is in 90 degree angles)
                dims = rotate_vector(vector=self.dimensions[m], quaternion=self.model_transforms[m])
                dims = np.absolute(dims)
                dims = tuple(dims)

                pose_msg = PoseStamped()
                pose_msg.header = image_msg.header
                CONVERT_SCALE_CM_TO_METERS = 100
                pose_msg.pose.position.x = loc[0] / CONVERT_SCALE_CM_TO_METERS
                pose_msg.pose.position.y = loc[1] / CONVERT_SCALE_CM_TO_METERS
                pose_msg.pose.position.z = loc[2] / CONVERT_SCALE_CM_TO_METERS
                pose_msg.pose.orientation.x = transformed_ori[0]
                pose_msg.pose.orientation.y = transformed_ori[1]
                pose_msg.pose.orientation.z = transformed_ori[2]
                pose_msg.pose.orientation.w = transformed_ori[3]

                # offset along object's z-axis,
                # so that the detected pose is located at the object surface
                pose_matrix = np.eye(4)#
                pose_matrix[0:3, 3] = np.array([pose_msg.pose.position.x,pose_msg.pose.position.y,pose_msg.pose.position.z])#
                pose_matrix[0:3, 0:3] = self.quaternion_to_matrix(pose_msg.pose.orientation)#
                z_offset = np.eye(4)#
                z_offset[2, 3] = self.config_detect.dimensions[self.config_detect.object_name][2] * 0.5 / CONVERT_SCALE_CM_TO_METERS#
                pose_matrix_offset = np.dot(pose_matrix, z_offset)#
                # overwrite pose_msg.position
                pose_msg.pose.position.x = pose_matrix_offset[0,3]#
                pose_msg.pose.position.y = pose_matrix_offset[1,3]#
                pose_msg.pose.position.z = pose_matrix_offset[2,3]#

                # Project to 2D image plane
                pose_2d = Pose2D()#
                fx = camera_info.K[0]#
                fy = camera_info.K[4]#
                K_matrix = np.asarray(camera_info.K).reshape((3, 3))#
                pose_2d_matrix = np.dot(K_matrix, np.array([[pose_msg.pose.position.x],[pose_msg.pose.position.y],[pose_msg.pose.position.z]]) ) / pose_msg.pose.position.z #
                pose_2d.x = pose_2d_matrix[0] #u(pixel)
                pose_2d.y = pose_2d_matrix[1] #v(pixel)
                pose_2d.theta = 0#

                # Look for the corresponding depth value
                curr_depth_img = self.cv_bridge.imgmsg_to_cv2(depth_msg)#
                CONVERT_SCALE_MM_TO_METERS = 1000#
                # print(curr_depth_img.shape)
                if int(pose_2d.y) < curr_depth_img.shape[0] and (pose_2d.x) < curr_depth_img.shape[1]: 
                    if int(pose_2d.y) > 0 and int(pose_2d.x) > 0:
                        depth_read = curr_depth_img[int(pose_2d.y), int(pose_2d.x)]  #mm

                        # Project to 3D again
                        xyz_3d = np.dot(np.linalg.inv(K_matrix), depth_read * np.array([pose_2d.x[0],pose_2d.y[0],1.0]).transpose()) / CONVERT_SCALE_MM_TO_METERS  # XYZ (m) in camera frame
                        # print('xyz_3d:', xyz_3d)
                        # print('pose_2d.x:', pose_2d.x[0], 'pose_2d.y:',pose_2d.y[0])

                        
                        # If multiple objects exist,
                        # find the closest one.
                        if xyz_3d[2] < z_min:#
                            z_min = xyz_3d[2]#
                            # write results to output msg
                            pose_comp.header = image_msg.header#
                            pose_comp.pose.position.x = xyz_3d[0]#
                            pose_comp.pose.position.y = xyz_3d[1]#
                            pose_comp.pose.position.z = xyz_3d[2]#
                            pose_comp.pose.orientation = pose_msg.pose.orientation#

                # Publish
                self.pubs[m].publish(pose_msg)
                self.pub_dimension[m].publish(str(dims))
                self.pub_2DPosition[m].publish(pose_2d)#
                

                # Add to Detection3DArray
                detection = Detection3D()
                hypothesis = ObjectHypothesisWithPose()
                hypothesis.id = self.class_ids[result["name"]]
                hypothesis.score = result["score"]
                hypothesis.pose.pose = pose_msg.pose
                detection.results.append(hypothesis)
                detection.bbox.center = pose_msg.pose
                detection.bbox.size.x = dims[0] / CONVERT_SCALE_CM_TO_METERS
                detection.bbox.size.y = dims[1] / CONVERT_SCALE_CM_TO_METERS
                detection.bbox.size.z = dims[2] / CONVERT_SCALE_CM_TO_METERS
                detection_array.detections.append(detection)

                # Draw the cube
                if None not in result['projected_points']:
                    points2d = []
                    for pair in result['projected_points']:
                        points2d.append(tuple(pair))
                    draw.draw_cube(points2d, self.draw_colors[m])

            # Publish
            #print(i_r,pose_comp.pose.position.z)#
            self.pub_comp[m].publish(pose_comp)#

            # Publish the belief image
            if publish_belief_img:
                belief_img = self.cv_bridge.cv2_to_imgmsg(np.array(im_belief)[..., ::-1], "bgr8")
                belief_img.header = camera_info.header
                self.pub_belief[m].publish(belief_img)

        # Publish the image with results overlaid
        rgb_points_img = CvBridge().cv2_to_imgmsg(np.array(im)[..., ::-1], "bgr8")
        rgb_points_img.header = camera_info.header
        self.pub_rgb_dope_points.publish(rgb_points_img)
        self.pub_camera_info.publish(camera_info)
        self.pub_detections.publish(detection_array)
        self.publish_markers(detection_array)

    def publish_markers(self, detection_array):
        # Object markers
        class_id_to_name = {class_id: name for name, class_id in self.class_ids.items()}
        markers = MarkerArray()
        for i, det in enumerate(detection_array.detections):
            name = class_id_to_name[det.results[0].id]
            color = self.draw_colors[name]

            # cube marker
            marker = Marker()
            marker.header = detection_array.header
            marker.action = Marker.ADD
            marker.pose = det.bbox.center
            marker.color.r = color[0] / 255.0
            marker.color.g = color[1] / 255.0
            marker.color.b = color[2] / 255.0
            marker.color.a = 0.4
            marker.ns = "bboxes"
            marker.id = i
            marker.type = Marker.CUBE
            marker.scale = det.bbox.size
            markers.markers.append(marker)

            # text marker
            marker = Marker()
            marker.header = detection_array.header
            marker.action = Marker.ADD
            marker.pose = det.bbox.center
            marker.color.r = color[0] / 255.0
            marker.color.g = color[1] / 255.0
            marker.color.b = color[2] / 255.0
            marker.color.a = 1.0
            marker.id = i
            marker.ns = "texts"
            marker.type = Marker.TEXT_VIEW_FACING
            marker.scale.x = 0.05
            marker.scale.y = 0.05
            marker.scale.z = 0.05
            marker.text = '{} ({:.2f})'.format(name, det.results[0].score)
            markers.markers.append(marker)

            # mesh marker
            try:
                marker = Marker()
                marker.header = detection_array.header
                marker.action = Marker.ADD
                marker.pose = det.bbox.center
                marker.color.r = color[0] / 255.0
                marker.color.g = color[1] / 255.0
                marker.color.b = color[2] / 255.0
                marker.color.a = 0.7
                marker.ns = "meshes"
                marker.id = i
                marker.type = Marker.MESH_RESOURCE
                marker.scale.x = self.mesh_scales[name]
                marker.scale.y = self.mesh_scales[name]
                marker.scale.z = self.mesh_scales[name]
                marker.mesh_resource = self.meshes[name]
                markers.markers.append(marker)
            except KeyError:
                # user didn't specify self.meshes[name], so don't publish marker
                pass

        for i in range(len(detection_array.detections), self.prev_num_detections):
            for ns in ["bboxes", "texts", "meshes"]:
                marker = Marker()
                marker.action = Marker.DELETE
                marker.ns = ns
                marker.id = i
                markers.markers.append(marker)
        self.prev_num_detections = len(detection_array.detections)

        self.pub_markers.publish(markers)


def rotate_vector(vector, quaternion):
    q_conj = tf.transformations.quaternion_conjugate(quaternion)
    vector = np.array(vector, dtype='float64')
    vector = np.append(vector, [0.0])
    vector = tf.transformations.quaternion_multiply(q_conj, vector)
    vector = tf.transformations.quaternion_multiply(vector, quaternion)
    return vector[:3]


def main():
    """Main routine to run DOPE"""

    # Initialize ROS node
    rospy.init_node('dope')
    DopeNode()

    try:
        rospy.spin()
    except rospy.ROSInterruptException:
        pass


if __name__ == "__main__":
    main()
